/* eslint-disable linebreak-style */
const question = [
  {
    id: 1,
    title: 'javascript',
    meetup: 1,
    body: 'what is javascript?',
    upvotes: 25,
    downvotes: 10,
    createdBy: 1,
    createdOn: new Date(),
  },
  {
    id: 2,
    title: 'c++',
    meetup: 2,
    body: 'how long can it take to learn c++?',
    upvotes: 30,
    downvotes: 15,
    createdBy: 2,
    createdOn: new Date(),
  },
  {
    id: 3,
    title: 'javascript',
    meetup: 3,
    body: 'how can i install node.js?',
    upvotes: 32,
    downvotes: 20,
    createdBy: 3,
    createdOn: new Date(),
  },
  {
    id: 4,
    title: 'java',
    meetup: 4,
    body: 'whatis the difference between java and javascript?',
    upvotes: 29,
    downvotes: 21,
    createdBy: 4,
    createdOn: new Date(),
  },
  {
    id: 5,
    title: 'java',
    meetup: 5,
    body: 'what is java used for?',
    upvotes: 29,
    downvotes: 21,
    createdBy: 5,
    createdOn: new Date(),
  },
];
export default question;
